### ISSUE TITLE
yo sanic quick question

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/sanicbtw#3]
do you mind if i port the mic'd up SC to mine? i'll credit you and everything

**Comment by SanicBTW** [comment]
what

**Comment by fnfporterhi** [comment]
i have the zip file that can port the engine to html5, do you mind if i do that on my git? i know there's one, just asking

**Comment by SanicBTW** [comment]
why would you want to publish the page by yourself if there is one already tho, i mean i wouldnt care if you actually made changes to the source code then its none of my business but as long as you give credits i dont mind

**Comment by fnfporterhi** [comment]
oh okay i'm sorry

**Comment by SanicBTW** [comment]
yo wsp, once i fully finish working on implementing the remaining features on HTML5 I will update the license and sharing policies
